"""Open a branch and PR via GitHub API."""

import base64
import os
from pathlib import Path
from typing import Any

import requests


def _check_env(var: str) -> str:
    val = os.environ.get(var)
    if not val:
        raise EnvironmentError(f"{var} is required but not set")
    return val


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _get_default_branch_sha(repo: str, headers: dict[str, str]) -> tuple[str, str]:
    """Return (sha, branch_name) for the default branch."""
    url = f"https://api.github.com/repos/{repo}"
    resp = requests.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    return data["default_branch"]


def _get_branch_sha(repo: str, branch: str, headers: dict[str, str]) -> str:
    """Get the HEAD commit SHA of an existing branch."""
    url = f"https://api.github.com/repos/{repo}/git/ref/heads/{branch}"
    resp = requests.get(url, headers=headers, timeout=30)
    resp.raise_for_status()
    return resp.json()["object"]["sha"]


def _create_branch(
    repo: str, base_branch: str, new_branch: str, headers: dict[str, str]
) -> None:
    """Create a new branch from the HEAD of base_branch."""
    sha = _get_branch_sha(repo, base_branch, headers)
    url = f"https://api.github.com/repos/{repo}/git/refs"
    payload = {
        "ref": f"refs/heads/{new_branch}",
        "sha": sha,
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()


def _upsert_file(
    repo: str,
    branch: str,
    path: str,
    content: str,
    message: str,
    headers: dict[str, str],
) -> None:
    """Create or update a single file on the given branch."""
    url = f"https://api.github.com/repos/{repo}/contents/{path}"

    # Check if file already exists (for SHA on update)
    params = {"ref": branch}
    get_resp = requests.get(url, headers=headers, params=params, timeout=30)

    payload: dict[str, Any] = {
        "message": message,
        "content": base64.b64encode(content.encode("utf-8")).decode("utf-8"),
        "branch": branch,
    }
    if get_resp.status_code == 200:
        payload["sha"] = get_resp.json()["sha"]

    resp = requests.put(url, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()


def _create_pr(
    repo: str,
    head_branch: str,
    base_branch: str,
    title: str,
    body: str,
    headers: dict[str, str],
) -> str:
    """Create a pull request and return its URL."""
    url = f"https://api.github.com/repos/{repo}/pulls"
    payload = {
        "title": title,
        "body": body,
        "head": head_branch,
        "base": base_branch,
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()["html_url"]


def open_pr(
    repo: str,
    model_name: str,
    plan: dict[str, Any],
    files: dict[str, Path],
) -> str:
    """Open a branch, commit generated files, and create a PR.

    Args:
        repo: "owner/repo" GitHub repository identifier.
        model_name: Name of the generated model (used for branch name).
        plan: The build plan dict (for PR description).
        files: Dict mapping logical names to Paths (from render.render_model).

    Returns:
        URL of the created PR.
    """
    token = _check_env("GITHUB_TOKEN")
    headers = _headers(token)
    branch = f"model-forge/{model_name}"
    base_branch = _get_default_branch_sha(repo, headers)

    # Create the feature branch
    _create_branch(repo, base_branch, branch, headers)

    # Commit each generated file
    for logical_name, path in files.items():
        content = path.read_text(encoding="utf-8")
        dbt_path = f"warehouse/models/generated/{path.name}"
        _upsert_file(repo, branch, dbt_path, content, f"add {path.name}", headers)

    # Build PR description from plan
    sources = ", ".join(r["table_name"] for r in plan.get("source_refs", []))
    dims = ", ".join(d["name"] for d in plan.get("dimensions", []))
    measures = ", ".join(m["name"] for m in plan.get("measures", []))

    body = (
        f"## Generated by Model Forge\n\n"
        f"**Prompt:** {plan.get('description', plan.get('model_name'))}\n\n"
        f"**DataHub sources:** {sources}\n\n"
        f"**Dimensions:** {dims}\n\n"
        f"**Measures:** {measures}\n\n"
        f"---\n"
        f"*This PR was auto-generated by [Model Forge](https://github.com/model-forge).*"
    )

    pr_title = f"Model Forge: add {model_name}"
    pr_url = _create_pr(repo, branch, base_branch, pr_title, body, headers)

    return pr_url
